---
# tasks file for jenkins
- name: update repos
  package: name=epel-release state=present

- name: installing java
  package: name=java state=present

- name: downloading jenkins repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: installing jenkins
  yum: name=jenkins state=present 

- name: starting jenkins
  service: name=jenkins state=started enabled=yes
